name: "Terraform"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #TF workspace
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        
      #azure login by main.tf
      - name: Azure Login
        run: az login --use-device-code
      
      #delete Rg
      - name: Azure Resource Configure
        run: az group delete -n INT493test --yes

      #TF init
      - name: Terraform Init
        run: terraform init

      #TF plan
      - name: Terraform Plan
        run: terraform plan
        
      #TF apply plan
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve